<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" 
		content="text/html;charset=utf-8" />
<script type="text/javascript">
    var baseUrl = '<?php echo $this->baseUrl ()?>'; 
    var autor = "Marcone Costa";
</script>
<?php echo $this->headMeta ();?>
<?php echo $this->headTitle ();?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/extjs/resources/css/ext-all.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/application.css' );?>
<?php $this->headScript()->appendFile( $this->baseUrl () . '/extjs/ext-debug.js') ?>
<?php  $this->headScript()->appendFile( $this->baseUrl () . '/javascripts/app.js') ?>
<?php echo $this->headScript() ?>

</head>
<body>
    <?php
    echo $this->layout ()->content;
    ?>
</body>
</html>
