<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <meta http-equiv="content-type" 
		content="text/html;charset=utf-8" />
<script type="text/javascript">
    var baseUrl = '<?php echo $this->baseUrl ()?>'; 
    var usuario = '<?php echo $this->usuario?>'; 
    var nomeUsuario = '<?php echo $this->nomeUsuario?>'; 
    var adminMenu = <?php echo $this->adminMenu ?>;
    var env = '<?php echo APPLICATION_ENV;?>';
    var tag_version = '<?php echo Zend_Registry::get('tag_version'); ?>';
</script>
<?php echo $this->headMeta ();?>
<?php echo $this->headTitle ();?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/extjs/resources/css/ext-all.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/application.css' );?>
 <?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl ('/codebase/dhtmlxgantt.css') );?>
<?php  //$this->headScript()->appendFile( $this->baseUrl () . '/javascripts/jsgantt.js') ?>
<?php  $this->headScript()->appendFile( $this->baseUrl ('/codebase/dhtmlxgantt.js')) ?>
<?php
if(APPLICATION_ENV=='production'){
    $this->headScript()->appendFile( $this->baseUrl () . '/extjs/ext-all.js');
}else{ 
    $this->headScript()->appendFile( $this->baseUrl () . '/extjs/ext-all-debug.js');
}
 $this->headScript()->appendFile( $this->baseUrl () . '/extjs/examples/ux/PreviewPlugin.js');
?>

<!-- arquivo principal da aplicação -->
<?php  $this->headScript()->appendFile( $this->baseUrl () . '/javascripts/main.js') ?>
<?php echo $this->headScript() ?>
</head>
<body>
    <?php
    echo $this->layout ()->content;
    ?>
</body>
</html>
